[package]
name = "randomizer"
version = "0.3.0"
authors = ["Kevin Marsolais <kevin@kevinmarsolais.co>", "Rich Fay <therichfay@gmail.com>"]
edition = "2021"
license = "GPL-2.0-or-later"
build = "../randomizer/build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
albw = { path = "../albw" }
crc = "3.0.1"
fs_extra = "1.3.0"
linked-hash-map = "0.5.4"
log = "0.4.14"
queue = "0.3.2-final"
path-absolutize = "3.0.14"
rand = { version = "0.8.3", features = ["std_rng"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.81"
simplelog = "0.12.0"
structopt = "0.3.21"
tempfile = "3.3.0"
toml = "0.7.2"
try-insert-ext = "0.1.0"
vec-drain-where = "1.0.1"

[dev-dependencies]
simplelog = "0.12.0"

[[bin]]
name = "albw-randomizer"
path = "./src/main.rs"

[[bin]]
name = "albw-plandomizer"
path = "./src/bin/plando.rs"
