array_width = 100
attr_fn_like_width = 100
struct_lit_width = 100
struct_variant_width = 100
chain_width = 100
single_line_if_else_max_width = 100
enum_discrim_align_threshold = 25
edition = "2021"
fn_params_layout = "Compressed"
format_macro_matchers = true
max_width = 100
overflow_delimited_expr = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 25
use_small_heuristics = "Max"
version = "Two"
