[package]
name = "sys"
version = "0.1.1"
authors = ["Kevin Marsolais <kevin@kevinmarsolais.co>", "Rich Fay <therichfay@gmail.com"]
edition = "2021"

[dependencies]
directories = "3.0.1"
json = "0.12.4"
serde = "1.0.125"
toml = "0.5.8"
log = "0.4.14"
