## Modifications to logic.
[logic]
## A Sword will be placed in Ravio's Shop
sword_in_shop = false
## The Bell will be placed in Ravio's Shop
bell_in_shop = false
## The Pouch will be placed in Ravio's Shop
pouch_in_shop = false
## The Pegasus Boots will be placed in Ravio's Shop
boots_in_shop = false
## Include the Super Lamp and Super Net in the shuffled item pool
super_items = false
## Exclude all minigames (Cucco Ranch, both Rupee Rushes, Hyrule Hotfoot, Treacherous Tower, and Octoball Derby)
minigames_excluded = false
## Skip the Trials in Lorule Castle
skip_trials = false
## Guarantees the Bow of Light will be placed *somewhere* in Lorule Castle
bow_of_light_in_castle = false
## Place items using logic that potentially requires glitches to complete
glitched_logic = false
## Swordless Mode. Removes all Swords from the game. You will need the Net to play Tennis with Yuganon.
swordless_mode = false

[options]
## Experimental option to change Hyrule's lighting until you visit Lorule for the first time.
## Causes performance issues on console.
night_mode = false

[exclusions]
'exclusions' = [
#    'Great Rupee Fairy',
#    'Thief Girl Cave'
]