## Modifications to logic.
[logic]

## Logic Mode. Choose one of: "Normal", "Hard", "GlitchBasic", "GlitchAdvanced", "GlitchHell", or "NoLogic"
mode = "Normal"

## Randomizes the Pendants and Portraits between Hyrule and Lorule dungeons
randomize_dungeon_prizes = true

## The number of Portraits (0-7) needed to trigger the Hilda cutscene to open Lorule Castle
lc_requirement = 7

## Guarantees one of the following weapons will be placed in Ravio's Shop: Sword, Bow, Hammer, Fire Rod, Ice Rod, or Bombs
assured_weapon = false

## The Bell will be placed in Ravio's Shop
bell_in_shop = false

## The Pouch will be placed in Ravio's Shop
pouch_in_shop = false

## The Pegasus Boots will be placed in Ravio's Shop
boots_in_shop = false

## Maiamai Madness. Shuffles Maiamai into the pool, adding 100 more locations
maiamai_madness = false

## Pre-activates all Weather Vanes (Note: No trackers currently support this)
vanes_activated = false

## Include the Super Lamp and Super Net in the shuffled item pool
super_items = false

## Exclude all minigames (Cucco Ranch, both Rupee Rushes, Hyrule Hotfoot, Treacherous Tower, and Octoball Derby)
minigames_excluded = false

## Skip the Trials in Lorule Castle
skip_trials = false

## Guarantees the Bow of Light will be placed *somewhere* in Lorule Castle (including possibly Zelda)
bow_of_light_in_castle = false

## Don't require Lamp. If 'true', the player may have to cross dark rooms without a light source. If you're not sure, select 'false'.
lampless = false

## Swordless Mode. Removes all Swords from the game. You will need the Net to play Tennis with Yuganon.
swordless_mode = false

## Options (no effect on logic)
[options]

## Alters treasure chest sizes depending on their contents: Large for Progression items, Small for everything else.
chest_size_matches_contents = false

## Experimental option to change lighting until you use Portals for the first time.
## Causes performance issues on console.
night_mode = false

## Exclude a specific check from having progression items. A random junk item will be placed there instead.
## Every check in the game has a *unique* name that can be placed here, consult a spoiler log for a complete list.
## Remove the "#" before a check to uncomment it and make sure it's excluded, or place a "#" in front to include it
[exclusions]
"exclusions" = [
#   "Great Rupee Fairy",
#   "Master Sword Pedestal",
#   "Zelda"
]