[package]
name = "bytey"
version = "0.1.0"
authors = ["Kevin Marsolais <kevin@kevinmarsolais.co>", "Rich Fay <therichfay@gmail.com>"]
edition = "2021"

[dependencies]
bytey-macro = { path = "../bytey-macro" }